################# DATA LOADER PARAMETERS

SAVE_MAX_IMAGES = 5000
MAX_IMAGES = 0
IMG_HEIGHT = 512 
IMG_WIDTH = 512
IMG_CHANNELS = 1
DEFAULT_PATH = '/mnt/dataC/HUGxGAN/data/HUGxGAN_512.hdf5'
DATA_NAME = 'cxr8'
