################ MODEL PARAMETERS

# MODEL TRAINING PARAMETERS
BATCH_SIZE = 1
POOL_SIZE = 50
NGF = 32
NDF = 64

# HYPER PARAMETERS

LAMBDA_A =  10.0
LAMBDA_B =  10.0
LAMBDA_W = 10.0 # if WGAN with penalized gradient

BASE_LR = 0.0002
MAX_STEP = 100
GEN_FREQ = 1
NET_VERSION = 'tensorflow'

DO_FLIPPING = 1
SKIP = True

# PRINT OPTION
SAVE_IMAGES = 5
